version: '3.2'

services:
    zookeeper:
        build: ./zookeeper
        # Keep it running.  
        tty: true
        
    storm-nimbus:
        build: ./storm-nimbus
        links:
            - zookeeper
            - cassandra
        tty: true
        # To access the Storm UI from our host machine.  
        ports:
            - 8080:8080
        volumes:
            - './storm-nimbus:/theproject'

    storm-supervisor:
        build: ./storm-supervisor
        links:
            - zookeeper
            - storm-nimbus
            - cassandra
        tty: true

    cassandra:
        build: ./cassandra
        volumes:
            - './cassandra/src:/src'
        ports:
            - 7199:7199
            - 9042:9042
        tty: true


# Host volume used to store our code on the master node (Nimbus).
volumes:
    storm-nimbus:
